const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let companies=[],adminCompany=null,servers=[],lastVersion='';
async function api(action,options={}){const r=await fetch(`api.php?action=${action}${options.query?'&'+new URLSearchParams(options.query):''}`,{method:options.body?'POST':'GET',headers:{'Content-Type':'application/json'},body:options.body?JSON.stringify(options.body):null});if(r.status===401){location.href='login.php';throw Error('Sessionen har gått ut')}const j=await r.json();if(!r.ok)throw Error(j.error||'Något gick fel');return j}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1800)}
async function loadCompanies(keep=true){companies=await api('companies');const old=keep?$('#companySelect').value:'';$('#companySelect').innerHTML=companies.filter(c=>+c.active).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(old&&companies.some(c=>c.id==old))$('#companySelect').value=old;renderCompanyList();await loadLogs()}
async function loadLogs(){const cid=$('#companySelect').value;if(!cid)return;const c=companies.find(x=>x.id==cid);$('#companyInfo').innerHTML=c?.info?`<strong>Bra att veta:</strong> ${esc(c.info).replaceAll('\n','<br>')}`:'';const data=await api('logs',{query:{company_id:cid,date:$('#logDate').value}});lastVersion=data.version;$('#startTime').value=data.start_time||'';$('#endTime').value=data.end_time||'';$('#logRows').innerHTML=data.rows.map(row=>+row.is_separator?`<tr class="separator-row"><td colspan="10"><div class="separator-line">${row.name?`<span class="separator-label">${esc(row.name)}</span>`:''}</div></td></tr>`:`<tr class="${row.values.done?'done-row':''}"><td>${esc(row.name)}</td>${['sync','update','updates','backup','reboot','unlocked','done'].map(f=>row.enabled_fields.includes(f)?`<td><input class="check" type="checkbox" data-server="${row.server_id}" data-field="${f}" ${row.values[f]?'checked':''}></td>`:'<td class="na">—</td>').join('')}<td><input class="check follow-check" type="checkbox" data-server="${row.server_id}" data-field="follow_up" ${+row.follow_up?'checked disabled':''}></td><td class="comment"><textarea data-server="${row.server_id}" data-comment placeholder="Kommentar…">${esc(row.comment||'')}</textarea></td></tr>`).join('');$('#empty').style.display=data.rows.filter(x=>!+x.is_separator).length?'none':'block'}
async function saveLog(el,field,value){$('#syncState').textContent='Sparar…';$('#syncState').classList.add('saving');await api('log_save',{body:{server_id:+el.dataset.server,date:$('#logDate').value,field,value}});$('#syncState').textContent='Synkad';$('#syncState').classList.remove('saving')}
async function saveDailyTime(field,value){$('#syncState').textContent='Sparar…';$('#syncState').classList.add('saving');const saved=await api('daily_log_save',{body:{company_id:+$('#companySelect').value,date:$('#logDate').value,field,value}});lastVersion=saved.updated_at;$('#syncState').textContent='Synkad';$('#syncState').classList.remove('saving')}
function renderCompanyList(){ $('#companyList').innerHTML=companies.map(c=>`<button data-company="${c.id}" class="${adminCompany==c.id?'selected':''}"><span>${esc(c.name)}</span><small>${+c.active?'Aktiv':'Inaktiv'}</small></button>`).join('');$('#reportCompanySelect').innerHTML=companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('') }
async function chooseCompany(id){adminCompany=+id;renderCompanyList();const c=companies.find(x=>x.id==id),f=$('#companyForm');f.classList.remove('hidden');f.id.value=c.id;f.name.value=c.name;f.info.value=c.info;f.active.checked=+c.active;$('#deleteCompany').disabled=false;servers=await api('servers',{query:{company_id:id}});renderServers();$('#serverHint').textContent=`Servrar hos ${c.name}`;$('#serverForm').classList.add('hidden')}
function renderServers(){ $('#serverList').innerHTML=servers.map((s,i)=>`<div class="server-row"><button class="edit-server ${+s.is_separator?'separator-admin':''}" data-server-edit="${s.id}"><span>${+s.is_separator?'— '+(esc(s.name)||'Avdelare')+' —':esc(s.name)}</span><small>${+s.is_separator?'Avdelare':(+s.active?'Aktiv':'Inaktiv')}</small></button><div class="reorder"><button data-move="up" data-id="${s.id}" ${i===0?'disabled':''} title="Flytta upp">↑</button><button data-move="down" data-id="${s.id}" ${i===servers.length-1?'disabled':''} title="Flytta ned">↓</button></div></div>`).join('') }
function editServer(id){const s=servers.find(x=>x.id==id),f=$('#serverForm'),separator=+s.is_separator;f.classList.remove('hidden');f.id.value=s.id;f.name.value=s.name;f.sort_order.value=s.sort_order;f.is_separator.value=separator?1:0;f.active.checked=+s.active;$('#serverNameLabel').firstChild.textContent=separator?'Rubrik (valfri)':'Servernamn';f.name.required=!separator;$$('.server-only').forEach(x=>x.classList.toggle('hidden',separator));$$('[name=fields]').forEach(x=>x.checked=s.enabled_fields.includes(x.value));$('#deleteServer').disabled=false}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.addEventListener('click',async e=>{try{if(e.target.closest('.nav')){$$('.nav,.view').forEach(x=>x.classList.remove('active'));e.target.closest('.nav').classList.add('active');$('#'+e.target.closest('.nav').dataset.view).classList.add('active');if(e.target.closest('.nav').dataset.view==='admin'){loadHistory();loadFollowups();loadUsers()}}if(e.target.closest('[data-company]'))chooseCompany(e.target.closest('[data-company]').dataset.company);if(e.target.closest('[data-server-edit]'))editServer(+e.target.closest('[data-server-edit]').dataset.serverEdit);if(e.target.closest('[data-move]')){const b=e.target.closest('[data-move]');await api('server_reorder',{body:{id:+b.dataset.id,direction:b.dataset.move}});await chooseCompany(adminCompany);await loadLogs()}}catch(x){toast(x.message)}})
$('#companySelect').onchange=loadLogs;$('#logDate').onchange=loadLogs;
$('#logRows').onchange=e=>{if(e.target.matches('.check')){if(e.target.dataset.field==='done')e.target.closest('tr').classList.toggle('done-row',e.target.checked);saveLog(e.target,e.target.dataset.field,e.target.checked).catch(x=>toast(x.message))}};$('#startTime').onchange=e=>saveDailyTime('start_time',e.target.value).catch(x=>toast(x.message));$('#endTime').onchange=e=>saveDailyTime('end_time',e.target.value).catch(x=>toast(x.message));let timer;$('#logRows').oninput=e=>{if(e.target.matches('[data-comment]')){clearTimeout(timer);timer=setTimeout(()=>saveLog(e.target,'comment',e.target.value).catch(x=>toast(x.message)),500)}};$('#logRows').onfocusout=e=>{if(e.target.matches('[data-comment]')){clearTimeout(timer);saveLog(e.target,'comment',e.target.value).catch(x=>toast(x.message))}};
$('#newCompany').onclick=()=>{const f=$('#companyForm');f.reset();f.id.value='';f.active.checked=true;f.classList.remove('hidden');$('#deleteCompany').disabled=true};
$('#companyForm').onsubmit=async e=>{e.preventDefault();const f=e.target;await api('company_save',{body:{id:f.id.value||null,name:f.name.value,info:f.info.value,active:f.active.checked}});toast('Företaget sparades');await loadCompanies();if(f.id.value)chooseCompany(f.id.value)};
$('#deleteCompany').onclick=async()=>{const id=$('#companyForm').id.value;if(id&&confirm('Ta bort företaget, dess servrar och alla loggar?')){await api('company_delete',{body:{id}});adminCompany=null;$('#companyForm').classList.add('hidden');$('#serverForm').classList.add('hidden');await loadCompanies()}};
function newServerForm(separator=false){if(!adminCompany)return toast('Välj först ett företag');const f=$('#serverForm');f.reset();f.id.value='';f.is_separator.value=separator?1:0;f.active.checked=true;f.sort_order.value=servers.length?Math.max(...servers.map(s=>+s.sort_order))+10:10;$('#serverNameLabel').firstChild.textContent=separator?'Rubrik (valfri)':'Servernamn';f.name.required=!separator;$$('.server-only').forEach(x=>x.classList.toggle('hidden',separator));$$('[name=fields]').forEach(x=>x.checked=!separator);f.classList.remove('hidden');$('#deleteServer').disabled=true}
$('#newServer').onclick=()=>newServerForm(false);$('#newSeparator').onclick=()=>newServerForm(true);
$('#serverForm').onsubmit=async e=>{e.preventDefault();const f=e.target;await api('server_save',{body:{id:f.id.value||null,company_id:adminCompany,name:f.name.value,sort_order:+f.sort_order.value,is_separator:+f.is_separator.value,active:f.active.checked,enabled_fields:$$('[name=fields]:checked').map(x=>x.value)}});toast(+f.is_separator.value?'Avdelaren sparades':'Servern sparades');await chooseCompany(adminCompany);await loadLogs()};
$('#deleteServer').onclick=async()=>{const id=$('#serverForm').id.value;if(id&&confirm('Ta bort servern och dess loggar?')){await api('server_delete',{body:{id}});await chooseCompany(adminCompany);await loadLogs()}};
async function loadHistory(){const h=await api('history');$('#history').innerHTML=h.length?h.map(x=>`<div class="row"><span>${x.log_date}</span><span>${esc(x.company_name)}</span><span>${esc(x.server_name)}</span><button class="danger" data-log-delete="${x.id}">Ta bort</button></div>`).join(''):'<p class="muted">Inga händelser ännu.</p>'}
async function loadUsers(){const users=await api('users'),current=document.body.dataset.currentUser;$('#userList').innerHTML=users.map(x=>`<div class="user-row"><span><strong>${esc(x.username)}</strong><small>${x.username===current?'Inloggad nu':'Skapad '+esc(x.created_at.slice(0,10))}</small></span><button class="danger" data-user-delete="${x.id}" ${x.username===current?'disabled':''}>Ta bort</button></div>`).join('')}
async function loadFollowups(){const rows=await api('followups');$('#followups').innerHTML=rows.length?rows.map(x=>`<article class="followup-item"><div class="followup-heading"><strong>${esc(x.company_name)}</strong><span>${esc(x.server_name)}</span><time>${x.log_date}</time></div><div class="followup-source"><b>Kommentar från loggen</b><p>${x.comment?esc(x.comment):'Ingen kommentar angiven.'}</p></div><label class="resolution-label">Vad har åtgärdats?<textarea data-resolution="${x.id}" placeholder="Beskriv åtgärden…"></textarea></label><div class="followup-footer"><button class="primary" data-resolve="${x.id}">Åtgärdad</button></div></article>`).join(''):'<p class="followup-empty">✓ Inget väntar på uppföljning.</p>'}
$('#refreshHistory').onclick=loadHistory;$('#history').onclick=async e=>{if(e.target.dataset.logDelete&&confirm('Ta bort denna loggrad?')){await api('log_delete',{body:{id:+e.target.dataset.logDelete}});loadHistory();loadLogs()}};
$('#refreshFollowups').onclick=loadFollowups;$('#followups').onclick=async e=>{if(e.target.dataset.resolve){const id=+e.target.dataset.resolve,comment=$(`[data-resolution="${id}"]`).value.trim();if(!comment)return toast('Skriv vad som har åtgärdats');try{await api('followup_resolve',{body:{id,comment}});toast('Uppföljningen är åtgärdad');await loadFollowups();await loadLogs()}catch(x){toast(x.message)}}};
$('#createFollowupReport').onclick=()=>{const id=$('#reportCompanySelect').value;if(id)window.open(`report.php?company_id=${encodeURIComponent(id)}`,'_blank')};
$('#newUser').onclick=()=>{$('#userForm').reset();$('#userForm').classList.remove('hidden')};$('#cancelUser').onclick=()=>$('#userForm').classList.add('hidden');$('#userForm').onsubmit=async e=>{e.preventDefault();try{await api('user_save',{body:{username:e.target.username.value,password:e.target.password.value}});toast('Användaren skapades');e.target.classList.add('hidden');await loadUsers()}catch(x){toast(x.message)}};$('#userList').onclick=async e=>{if(e.target.dataset.userDelete&&confirm('Ta bort användaren?')){try{await api('user_delete',{body:{id:+e.target.dataset.userDelete}});toast('Användaren togs bort');await loadUsers()}catch(x){toast(x.message)}}};
$('#importButton').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!confirm('Importen ersätter alla företag, servrar och loggar med innehållet i backupen. Användarkonton behålls. Fortsätta?')){e.target.value='';return}const form=new FormData();form.append('backup',file);$('#importStatus').textContent='Importerar och validerar backup…';try{const r=await fetch('api.php?action=import',{method:'POST',body:form});if(r.status===401){location.href='login.php';return}const result=await r.json();if(!r.ok)throw Error(result.error||'Importen misslyckades');$('#importStatus').textContent=`Återställningen är klar: ${result.companies} företag, ${result.servers} servrar och ${result.logs} loggar.`;toast('Backupen importerades');adminCompany=null;await loadCompanies(false);await loadFollowups();await loadHistory()}catch(x){$('#importStatus').textContent=`Importen avbröts: ${x.message}`;toast(x.message)}finally{e.target.value=''}};
setInterval(async()=>{if(!$('#log').classList.contains('active')||!$('#companySelect').value)return;try{const d=await api('logs',{query:{company_id:$('#companySelect').value,date:$('#logDate').value}});if(d.version!==lastVersion&&!document.activeElement.matches('[data-comment]'))loadLogs()}catch{}},2000);
setInterval(()=>api('session').catch(()=>{}),30000);
loadCompanies(false).catch(e=>toast(e.message));
