<?php require __DIR__.'/db.php'; db(); ?>
<!doctype html><html lang="sv"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Serverloggen</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="extras.css"><link rel="stylesheet" href="time.css"><link rel="stylesheet" href="done.css"><link rel="stylesheet" href="followup.css"><link rel="stylesheet" href="followup-warning.css"><link rel="stylesheet" href="export.css"></head>
<body><header><div><span class="mark">SL</span><div><h1>Serverloggen</h1><small>Daglig driftkontroll</small></div></div><nav><button class="nav active" data-view="log">Logga</button><button class="nav" data-view="admin">Administration</button></nav></header>
<main>
 <section id="log" class="view active"><div class="toolbar card"><label>Företag<select id="companySelect"></select></label><label>Loggdatum<input id="logDate" type="date" value="<?=date('Y-m-d')?>"></label><label>Starttid<input id="startTime" type="time"></label><label>Sluttid<input id="endTime" type="time"></label><span id="syncState" class="status">Synkad</span></div><div id="companyInfo" class="info card"></div><div class="card tablewrap"><table><thead><tr><th>Server</th><?php foreach(SERVICES as $x):?><th><?=['unlocked'=>'Upplåst','done'=>'Klar'][$x]??ucfirst($x)?></th><?php endforeach?><th>Följ upp</th><th>Kommentar</th></tr></thead><tbody id="logRows"></tbody></table><div id="empty" class="empty">Inga aktiva servrar finns på företaget.</div></div></section>
 <section id="admin" class="view"><div class="admin-grid"><div class="card panel"><div class="panel-title"><h2>Företag</h2><button id="newCompany" class="primary">+ Nytt</button></div><div id="companyList" class="list"></div><form id="companyForm" class="form hidden"><input type="hidden" name="id"><label>Namn<input name="name" required></label><label>Bra att veta<textarea name="info" rows="4"></textarea></label><label class="inline"><input name="active" type="checkbox" checked> Aktivt företag</label><div><button class="primary">Spara</button><button type="button" class="danger" id="deleteCompany">Ta bort</button></div></form></div>
 <div class="card panel"><div class="panel-title"><h2>Servrar</h2><div class="server-actions"><button id="newSeparator">+ Avdelare</button><button id="newServer" class="primary">+ Ny server</button></div></div><p id="serverHint" class="muted">Välj ett företag.</p><div id="serverList" class="list server-list"></div><form id="serverForm" class="form hidden"><input type="hidden" name="id"><input type="hidden" name="sort_order"><input type="hidden" name="is_separator"><label id="serverNameLabel">Servernamn<input name="name" required></label><label class="inline server-only"><input name="active" type="checkbox" checked> Aktiv server</label><fieldset class="server-only"><legend>Aktiva fält</legend><?php foreach(SERVICES as $x):?><label class="inline"><input type="checkbox" name="fields" value="<?=$x?>"> <?=['unlocked'=>'Upplåst','done'=>'Klar'][$x]??ucfirst($x)?></label><?php endforeach?></fieldset><div><button class="primary">Spara</button><button type="button" class="danger" id="deleteServer">Ta bort</button></div></form></div>
 <div class="card panel wide followup-panel"><div class="panel-title"><h2>Att följa upp</h2><button id="refreshFollowups">Uppdatera</button></div><div id="followups"></div></div><div class="card panel wide"><div class="panel-title"><h2>Senaste händelser</h2><div class="history-actions"><a class="button-link export-button" href="api.php?action=export">Exportera JSON</a><button id="refreshHistory">Uppdatera</button></div></div><div id="history"></div></div></div></section>
</main><div id="toast"></div><script src="app.js"></script></body></html>
